export const openrouterInfo = {
  name: "OpenRouter",
  baseUrl: "https://openrouter.ai/api/v1",
  modelFilters: [
    "openai/gpt-5.1",
    "anthropic/claude-haiku-4.5",
    "anthropic/claude-sonnet-4.5",
    "anthropic/claude-opus-4.1",
    "x-ai/grok-4",
    "qwen/qwen3-235b-a22b-2507",
    "deepseek/deepseek-v3.1-terminus",
    "qwen/qwen3-max",
  ],
  modelNames: {
    "openai/gpt-5.1": "GPT-5.1",
    "anthropic/claude-haiku-4.5": "Claude Haiku 4.5",
    "anthropic/claude-sonnet-4.5": "Claude Sonnet 4.5",
    "anthropic/claude-opus-4.1": "Claude Opus 4.1",
    "x-ai/grok-4": "Grok 4",
    "google/gemini-2.5-flash": "Gemini 2.5 Flash",
    "google/gemini-2.5-pro": "Gemini 2.5 Pro",
    "qwen/qwen3-235b-a22b-2507": "Qwen3",
    "deepseek/deepseek-v3.1-terminus": "DeepSeek V3.1 Terminus",
    "qwen/qwen3-max": "Qwen3 Max",
  } as Record<string, string>,
};
