import type { HostTool } from "@onlyoffice/ai-chat";
import { editor } from "../../library/editor";
import { defineTool } from "./defineTool";
import { ToolError } from "./ToolError";
import { optionalString, requireString } from "./validation";

export interface WriteMacroFix {
  keys: string[];
  hint: string;
}

export interface WriteMacroFactoryConfig {
  description: string;
  systemPrompt: string;
  fixes?: WriteMacroFix[];
}

interface WriteMacroResult {
  onlyoffice_id_result?: unknown;
  onlyoffice_id_error_message?: string;
}

function stripCodeFences(text: string): string {
  const trimmed = text.trim();
  const fenced = trimmed.match(
    /^```(?:[a-zA-Z0-9_-]+)?\s*\n([\s\S]*?)\n```\s*$/
  );
  return fenced ? fenced[1].trim() : trimmed;
}

function buildPrompt(
  systemPrompt: string,
  task: string,
  context: string
): string {
  return `${systemPrompt}

## Task
${task}

## Context
${context || "(none provided)"}

Return ONLY the raw JavaScript macro code. No markdown fences, no comments, no explanations.`;
}

export function createWriteMacroTool(
  config: WriteMacroFactoryConfig
): HostTool {
  return defineTool({
    name: "writeMacro",
    description: config.description,
    inputSchema: {
      type: "object",
      properties: {
        task: {
          type: "string",
          description:
            "Natural-language description of what the macro should accomplish. The code itself is generated by a code-specialist model — describe intent, target ranges/elements, and desired outcome rather than writing JavaScript.",
        },
        context: {
          type: "string",
          description:
            "Relevant context the code generator needs: readSheetContext output, column letters, header/data row bounds, sheet/slide/element names, prior tool results. Pass everything that would otherwise be required to author the macro by hand.",
        },
      },
      required: ["task"],
    },
    handler: async (params) => {
      const task = requireString(params, "task");
      const context = optionalString(params, "context") ?? "";

      if (!window.AI) {
        throw new ToolError("AI runtime not available");
      }
      const requestEngine = window.AI.Request.create(window.AI.ActionType.Code);
      if (!requestEngine) {
        throw new ToolError("Failed to create AI code request engine");
      }

      const prompt = buildPrompt(config.systemPrompt, task, context);
      const raw = await requestEngine.chatRequest(prompt);
      if (!raw || !raw.trim()) {
        throw new ToolError("Empty response from code profile");
      }
      const code = stripCodeFences(raw);

      Asc.scope.macroCode = code;
      Asc.scope.fixes = (config.fixes ?? []).map((f) => [f.keys, f.hint]);
      Asc.scope.fallbackHints = !!config.fixes;

      const result = await editor.callCommand<WriteMacroResult | undefined>(
        () => {
          try {
            // biome-ignore lint/security/noGlobalEval: writeMacro is designed to execute LLM-supplied macro code via eval (1:1 with the original plugin).
            const __result = eval(Asc.scope.macroCode);
            if (__result !== undefined && __result !== null) {
              return { onlyoffice_id_result: __result };
            }
            return undefined;
          } catch (e: unknown) {
            const err = e as { name?: string; message?: string };
            const em: string = err?.message || "";
            let hint = "";
            const FIXES = Asc.scope.fixes as Array<[string[], string]>;
            for (let fi = 0; fi < FIXES.length; fi++) {
              const keys = FIXES[fi][0];
              let matched = false;
              for (let ki = 0; ki < keys.length; ki++) {
                if (em.indexOf(keys[ki]) >= 0) {
                  matched = true;
                  break;
                }
              }
              if (matched) {
                hint = `\n\nFix: ${FIXES[fi][1]}`;
                break;
              }
            }
            if (!hint && Asc.scope.fallbackHints) {
              if (em.indexOf("Cannot read") >= 0 && /reading '\d+'/.test(em)) {
                hint =
                  "\n\nFix: Indexing undefined (e.g. ws.tables[5]). readSheetContext JSON is not accessible in macro — hardcode values as literals (let salaryCol = 'L'; let headerRow = 3;).";
              } else if (
                em.indexOf("Cannot read") >= 0 ||
                em.indexOf("not a function") >= 0
              ) {
                hint =
                  "\n\nHint: Discover available members: var r=[]; for(var k in obj) r.push(k+':'+typeof obj[k]); r.join('\\n')";
              }
            }
            return {
              onlyoffice_id_error_message: `${err?.name || "Error"}: ${em}${hint}`,
            };
          }
        }
      );

      if (result?.onlyoffice_id_error_message) {
        throw new ToolError(result.onlyoffice_id_error_message);
      }
      if (result && result.onlyoffice_id_result !== undefined) {
        return result.onlyoffice_id_result;
      }
      return "Macro executed successfully.";
    },
  });
}
